@startuml
start
:Inserisci dati utente;

if (Dati correttamente formattati?) then (si)
    if (Matricola già registrata nel sistema?) then (no)
    :Registra nuovo utente;
    else (si)
        :Mostra messaggio di errore
        (matricola utente già registrata);
    endif
else (no)
        :Mostra messaggio di errore
        (dati inseriti non validi);
endif
stop
@enduml
