@startuml
start
:Cerca utente;
if (Utente presente nel sistema?) then (si)
    :Seleziona utente;
    if(Utente ha prestiti attivi?) then (no)
        :Elimina utente;
    else (si)
        :Mostra messaggio di errore (utente ha prestiti attivi);
    endif
else (no)
:Mostra messaggio di errore (utente non presente nel sistema);
endif

stop
@enduml