@startuml
'skinparam classAttributeIconSize 0
skinparam nodesep 100

interface Filtro<T> {
    +controlla(): boolean
}

together {
    +interface Archiviabile<E> {
        +getLista(): List<E>
        +registra(): void
        +rimuovi(): void
        +modifica(): void
        +filtra(): List<E>
    }

    +interface Indicizzabile<K, V> {
        +ottieni(): V
        +contiene(): boolean
    }
}

+class Utente {
}

+class Libro{
}

+class Prestito{
}


+class Biblioteca {
    -archivioLibri: Indicizzabile<ISBN, Libro>
    -archivioUtenti: Indicizzabile<Matricola, Utente>
    -archivioPrestiti: Archiviabile<Prestito>

    +Biblioteca()
    +getPrestitiAttivi(): List<Prestito>
    +registraPrestito()
    +registraRestituzione()
    +salvaFile()
    +caricaFile()
}

+abstract class Gestore<E> {
    #lista: List<E>
}

together {
    +class GestoreLibri extends Gestore {

        -indiceISBN: Map<ISBN, Libro> {readOnly}

        +GestoreLibri()
    }


    +class GestoreUtenti extends Gestore {
        -indiceMatricola: Map<Matricola, Utente> {readOnly}

        +GestoreUtenti()
    }


    +class GestorePrestiti extends Gestore {

        +GestorePrestiti()
    }
}

Gestore -up-|> Archiviabile

Biblioteca --> Archiviabile
Biblioteca --> Indicizzabile

Indicizzabile -right-|> Archiviabile
Archiviabile .right.> Filtro

GestoreLibri .up.|> Indicizzabile
GestoreUtenti .up.|> Indicizzabile

GestoreUtenti --> "1..*" Utente
GestoreLibri --> "1..*" Libro
GestorePrestiti --> "1..*" Prestito
@enduml
