@startuml
skinparam classAttributeIconSize 0

+class Utente{
    -nome: String
    -cognome: String
    -matricola: String
    -email: String
    -prestitiAttivi: List<Prestito>

    +Utente()
    +getNome(): String
    +getCognome(): String
    +getMatricola(): String
    +getEmail(): String
    +getPrestitiAttivi(): List<Prestito>
    +modificaUtente(): Utente
    +verificaMatricola(): boolean
    +verificaEmail(): boolean
    +equals(): boolean
    +hashCode(): int
}


+class Libro{
    -titolo: String
    -autori: List<Autore>
    -annoPubblicazione: String
    -ISBN: String

    +Libro()
    +getTitolo(): String
    +getAutori(): List<Autore>
    +getAnnoPubblicazione(): String
    +getISBN(): String
    +aggiungiAutore(): void
    +modificaLibro(): Libro
    +verificaISBN(): boolean
    +equals(): boolean
    +hashCode(): int
}


+class Autore{
    -nome: String
    -cognome: String

    +getNome(): String
    +getCognome(): String
}


+class Prestito{
    -libro: Libro
    -utente: Utente
    -statoPrestito: StatoPrestito (enum)
    -scadenzaPrestito: LocalDate {readOnly}

    +getLibro(): Libro
    +getUtente(): Utente
    +getStatoPrestito(): StatoPrestito
    +getScadenzaPrestito(): LocalDate
    +isScaduto(): boolean
    +aggiornaStatoPrestito(): void
    +equals(): boolean
}

+enum StatoPrestito{
    ATTIVO,
    SALDATO
}


+class Biblioteca {
    -archivioLibri: ArchivioLibri
    -archivioUtenti: ArchivioUtenti
    -archivioPrestiti: ArchivioPrestiti

    +Biblioteca()
}


+interface ArchivioLibri {
    +aggiungiLibro(): void
    +rimuoviLibro(): void
    +cercaLibro(): Libro
}

+interface ArchivioUtenti {
    +registraUtente(): void
    +rimuoviUtente(): void
    +cercaMatricola(): Utente
    +cercaCognome(): List<Utente>
}

+interface ArchivioPrestiti {
    registraPrestito(): void
    saldaPrestito(): void
    visualizzaStoricoPrestiti(): void
}


+class GestoreLibri implements ArchivioLibri, Comparable {
    -mapLibri: Map<String, Libro>
    -listaLibri: List<Libro>

    +GestoreLibri()
    +aggiungiLibro()
    +rimuoviLibro()
    +cercaPerTitolo(): Libro
    +cercaPerAutore(): Libro
    +cercaPerISBN(): Libro
    +getElencoLibri(): Map<String, Libro>
    +compareTo()
}


+class GestoreUtenti implements ArchivioUtenti, Comparable{
    -mapUtenti: Map<String, Utente>
    -listaUtenti: List<Utente>

    +registraUtente(): void
    +rimuoviUtente(): void
    +cercaMatricola(): Utente
    +cercaCognome(): List<Utente>
    +getElencoUtenti(): Map<String, Utente>
    +compareTo()
}


+class GestorePrestiti implements ArchivioPrestiti, Comparable{
    -storicoPrestiti: List<Prestito>

    +registraPrestito()
    +restituisciPrestito()

    +getStoricoPrestiti()
    +getPrestitiAttivi()
    +compareTo()
}


Biblioteca "aggregazione" o-- ArchivioUtenti
Biblioteca "aggregazione" o-- ArchivioLibri
Biblioteca "aggregazione" o-- ArchivioPrestiti

Utente -- "1..3" Prestito
Libro -- "1..*" Autore

GestoreUtenti "aggregzione" o-- "1..*" Utente
GestoreLibri "aggregzione" o-- "1..*" Libro
GestorePrestiti "aggregzione" o-- "1..*" Prestito
@enduml
