@startuml
'skinparam classAttributeIconSize 0
skinparam nodesep 100

interface Filtro<T> {
    +controlla(T t): boolean
}

+abstract class Archivio<E> {
    -collezione: List<E>

    +registra(T t): void {abstract}
    +rimuovi(T t): void {abstract}
    +getCollezione(): List<E>
    +filtra(Filtro f): List<E>
}

+interface CollezioneConChiave<K, V> {
    +ottieni(K key): V
    +contiene(K key): boolean
}

+abstract class Persona{
    -nome: String
    -cognome: String

    +Persona()
    +getNome(): String
    +getCognome(): String
}

+class Utente extends Persona{
    -matricola: Matricola
    -email: IndirizzoEmail
    -prestitiAttivi: List<Prestito>

    +Utente()
    +getMatricola(): Matricola
    +getEmail(): IndirizzoEmail
    +modificaUtente(): Utente
    +compareTo(): int
}

+class Matricola {
    -matricola: String

    +Matricola()
    +setMatricola()
    +verifica(): boolean {static}
    +toString()
}

+class IndirizzoEmail {
    -indirizzo: String

    +IndirizzoEmail()
    +setIndirizzo()
    +verifica(): boolean {static}
    +toString()
}


+class Libro{
    -titolo: String
    -autori: List<Autore>
    -dataPubblicazione: LocalDate
    -numeroCopie: int
    -id: ISBN

    +Libro()
    +getTitolo(): String
    +getAutori(): List<Autore>
    +getAnnoPubblicazione(): String
    +getISBN(): ISBN
    +getNumeroCopie(): int
    +aggiungiAutore(): void
    +modificaLibro(): Libro
    +compareTo(): int
}

+class ISBN {
    -id: String

    +ISBN()
    +setId()
    +verifica(): boolean {static}
    +toString()
}

+class Autore extends Persona{
}


+class Prestito{
    -matricolaUtente: Matricola
    -idLibro: ISBN
    -statoPrestito: StatoPrestito
    -scadenzaPrestito: LocalDate

    +getIdLibro(): Libro
    +getMatricolaUtente(): Utente
    +getStatoPrestito(): StatoPrestito
    +getScadenzaPrestito(): LocalDate
    +setStatoPrestito(): void
    +isScaduto(): boolean
    +compareTo(): int
}

+enum StatoPrestito{
    ATTIVO,
    SALDATO
}


+class Biblioteca {
    -archivioLibri: Archivio<Libri>
    -archivioUtenti: Archivio<Utenti>
    -archivioPrestiti: Archivio<Prestiti>

    +Biblioteca()
    +salvaFile()
    +caricaFile()
}


+class GestoreLibri extends Archivio implements CollezioneConChiave {
    -indice: Map<ISBN, Libro>

    +GestoreLibri()
}


+class GestoreUtenti extends Archivio implements CollezioneConChiave {
    -indice: Map<Matricola, Utente>

    +GestoreUtenti()
}


+class GestorePrestiti extends Archivio {

    +GestorePrestiti()
}


Biblioteca --> Archivio
'Biblioteca ..> CollezioneConChiave

Archivio .right.> Filtro

Utente --> "1..3" Prestito
Utente --> Matricola
Utente ---> IndirizzoEmail
Libro ---> "1..*" Autore
Libro --> ISBN
Prestito --> Matricola
Prestito --> ISBN
Prestito --* StatoPrestito

GestoreUtenti --> "1..*" Utente
GestoreLibri --> "1..*" Libro
GestorePrestiti --> "1..*" Prestito
@enduml
