@startuml
skinparam classAttributeIconSize 0

+interface Archivio<T> {
    +registra(T t): void
    +rimuovi(T t): void
    +collezione(): Collection<T>
    +filtra(): Collection<T>
}

+interface CollezioneConChiave<K, V> {
    +ottieni(K key): V
}

+abstract class Persona{
    -nome: String
    -cognome: String

    +Persona()
    +getNome(): String
    +getCognome(): String
}

+class Utente extends Persona{
    -matricola: Matricola
    -email: IndirizzoEmail
    -prestitiAttivi: List<Prestito>

    +Utente()
    +getMatricola(): Matricola
    +getEmail(): IndirizzoEmail
    +modificaUtente(): Utente
    +compareTo(): int
}

+class Matricola {
    -matricola: String

    +Matricola()
    +setMatricola()
    +verifica(): boolean {static}
    +toString()
}

+class IndirizzoEmail {
    -indirizzo: String

    +IndirizzoEmail()
    +setIndirizzo()
    +verifica(): boolean {static}
    +toString()
}


+class Libro{
    -titolo: String
    -autori: List<Autore>
    -dataPubblicazione: LocalDate
    -id: ISBN

    +Libro()
    +getTitolo(): String
    +getAutori(): List<Autore>
    +getAnnoPubblicazione(): String
    +getId(): ISBN
    +aggiungiAutore(): void
    +modificaLibro(): Libro
    +compareTo(): int
}

+class ISBN {
    -id: ISBN

    +ISBN()
    +verifica(): boolean {static}
    +toString()
}

+class Autore extends Persona{
}


+class Prestito{
    -matricolaUtente: Matricola
    -idLibro: ISBN
    -statoPrestito: StatoPrestito (enum)
    -scadenzaPrestito: LocalDate

    +getIdLibro(): Libro
    +getMatricolaUtente(): Utente
    +getStatoPrestito(): StatoPrestito
    +getScadenzaPrestito(): LocalDate
    +setStatoPrestito(): void
    +isScaduto(): boolean
}

+enum StatoPrestito{
    ATTIVO,
    SALDATO
}


+class Biblioteca {
    -archivioLibri: Archivio<Libri>
    -archivioUtenti: Archivio<Utenti>
    -archivioPrestiti: Archivio<Prestiti>

    +Biblioteca()
    +salvaFile()
    +caricaFile()
}


+class GestoreLibri implements Archivio, CollezioneConChiave {
    -mapLibri: Map<ISBN, Libro>
    -listaLibri: List<Libro>

    +GestoreLibri()
}


+class GestoreUtenti implements Archivio, CollezioneConChiave {
    -mapUtenti: Map<Matricola, Utente>
    -listaUtenti: List<Utente>

    +GestoreUtenti()
}


+class GestorePrestiti implements Archivio {
    -storicoPrestiti: List<Prestito>

    +GestorePrestiti()
}


Biblioteca --> Archivio
Biblioteca --> CollezioneConChiave

Utente --> "1..3" Prestito
Utente --> Matricola
Utente ---> IndirizzoEmail
Libro ---> "1..*" Autore
Libro --> ISBN
Prestito --> Matricola
Prestito --> ISBN
Prestito --* StatoPrestito

GestoreUtenti --> "1..*" Utente
GestoreLibri --> "1..*" Libro
GestorePrestiti --> "1..*" Prestito
@enduml
