@startuml
actor G as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "Utente" as U
participant "Matricola" as M
participant "Email" as E
activate G
' ----- Inizio -----

G -> UI : Interazione con "Utenti"
deactivate G
activate UI
UI -> B : getCollezione
activate B
B --> UI : restituzione elenco Utenti
deactivate B
UI -> G : Mostra lista Utenti
activate G

G -> UI : Interazione con "Aggiungi Utente"
deactivate G

UI -> G : Mostra form di registrazione

activate G
G -> UI : Inserisce i dati utente
G -> UI : Conferma registrazione
deactivate G

' ----- Invio dati a Sistema -----
UI -> U : new Utente(nome,cognome,email,matricola)

activate U
U -> M : new Matricola(matricola)
activate M
M -> M : Matricola.verifica(matricola)
'deactivate UI

' ----- Controllo Sintassi Matricola -----
alt Sintassi Matricola Errata
    M -> UI : throw MatricolaInvalidaException
    deactivate M
    deactivate U
    'activate UI
    UI -> G : Mostra messaggio di errore riguardo la sintassi della matricola

    else Sintassi Matricola Valida
    M --> U : Restituzione Matricola
    deactivate M
end

' ----- Controllo Email -----

U -> E : new IndirizzoEmail(email)
E -> E : Email.verifica(email)

alt Email non valida (correzione)
    B -> UI : throw formatoNonValidoEmail
    deactivate B
    activate UI

    UI -> G : Visualizzazione errore Email duplicata

    activate G
    G -> UI : Corregge l'Email
    deactivate G


    UI -> B : newUtente(email)

    activate B
    UI -> B : Email.verifica(email

    deactivate UI
else Email non valida (annullamento)
    B -> UI : throw formatoNonValidoEmail
    deactivate B

    activate UI
    UI -> G : Visualizzazione errore Email duplicata


    activate G
    G -> UI : Annulla operazione
    deactivate G


    UI -> G : chiudi form di registrazione
deactivate UI

else Email Valida
B -> UI : true
activate UI
activate B

end

' ----- Controllo Matricola -----
UI -> B : GestioneUtenti.contiene(matricola)
deactivate UI
activate B
alt Matricola già esistente (correzione)

    B -> UI : throw matricolaDuplicata
    deactivate B
    activate UI


    UI -> G : Visualizzazione errore matricola duplicata


    activate G
    G -> UI : Corregge la matricola
    deactivate G


    UI -> B : newUtente(matricola)


    activate B
    UI -> B : GestioneUtenti.contiene(matricola)
    deactivate UI


else Matricola già esistente (annullamento)

    B -> UI : throw matricolaDuplicata
    deactivate B

    activate UI
    UI -> G : Visualizzazione errore matricola duplicata


    activate G
    G -> UI : Annulla operazione
    deactivate G


    UI -> G : chiudi form di registrazione
deactivate UI
else Matricola Unica

B -> UI : true
activate UI
activate B

end

' ----- Conclusione -----

UI -> B : addUtenti(Utente)

UI -> G : chiudi form di registrazione
deactivate UI
@enduml
