@startuml
actor Gestore
participant "GUI" as UI
participant "Biblioteca" as B

'  ---- Flusso principale -----
activate Gestore
Gestore -> UI : Interazione con "Libri"
deactivate Gestore
activate UI

UI -> B : getCollezione
activate B
B --> UI : restituisce elenco libri
deactivate B
UI -> Gestore : Mostra elenco dei libri
activate Gestore

Gestore -> UI : Seleziona campo da modificare
Gestore -> UI : Inserisce nuovo valore
deactivate Gestore
UI -> B : setTitolo
activate B
UI -> B : controlla(Titolo)
deactivate B

' ----- Verifica Dati -----
alt Dato non valido (annullamento)
    UI -> Gestore : Titolo ritorna al valore precedente
    activate Gestore
    Gestore -> UI : interazione per uscire dalla schermata
    deactivate Gestore
    UI -> Gestore : chiusura visualizzazione libro 


else Dato non valido (correzione)
    UI -> Gestore : Titolo ritorna al valore precedente
    activate Gestore
    Gestore -> UI : Inserisce un nuovo valore corretto
    deactivate Gestore
    UI -> B : setTitolo

else Dato valido
    UI -> Gestore : Titolo aggiornato correttamente

end

UI -> Gestore : Chiusura visualizzazione libri
deactivate UI

@enduml
