@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "ArchivioLibri" as AL
participant "ArchivioPrestiti" as AP

' CAMBIARE IN RIMUOVI PRESTITO ????

' ----- Inizio -----
activate G
G -> UI : Interazione con l'interazione per visualizzare i libri
deactivate G
activate UI
UI -> B : getArchivioLibri()
activate B

B --> UI : Restituzione dell'elenco dei libri
deactivate B
UI -> G : Mostra l'elenco dei libri
activate G
G -> UI : Seleziona l'utente da rimuovere
deactivate G

UI -> B : getStatoPrestito
activate B
B --> UI : StatoPrestito
deactivate B

' ---- Flusso alternativo -----
alt Presenza di un prestito attivo
    UI -> G : Disabilita l'interazione di rimozione del libro

else Nessun prestito attivo
    G -> UI : Interazione di rimozione del libro
    UI -> AL : archivioLibri.rimuovi(Libro)

end

deactivate UI

@enduml
