@startuml
skinparam actorStyle awesome

left to right direction

actor Gestore as G

package Sistema {
    usecase "Visualizzazione dell'elenco degli utenti" as UC5
    usecase "Registrazione di un utente" as UC6
    usecase "Modifica dei dati di un utente" as UC7
    usecase "Rimozione di un utente" as UC8
    usecase "Ricerca di utenti" as UC17

    usecase "Matricola duplicata" as UCA1
    usecase "E-Mail non valida" as UCA2
    usecase "Utente con prestiti attivi" as UCA3
}


UC6 ..> UC5 : <<include>>
UC7 ..> UC5 : <<include>>
UC8 ..> UC5 : <<include>>
UC17 ..> UC5 : <<include>>

UC6 <.. UCA1 : <<extend>>
UC7 <.. UCA1 : <<extend>>
UC6 <.. UCA2 : <<extend>>
UC7 <.. UCA2 : <<extend>>
UC8 <.. UCA3 : <<extend>>

G -- UC6
G -- UC7
G -- UC8
G -- UC17

@enduml
