@startuml
skinparam actorStyle awesome

left to right direction

actor Gestore as G

package Sistema {
    usecase "Visualizzazione del catalogo libri" as UC2
    usecase "Ricerca di libri" as UC11
    usecase "Registrazione di un libro" as UC12
    usecase "Modifica dei dati di un libro" as UC13
    usecase "Rimozione di un libro dal catalogo" as UC14

    usecase "ISBN duplicato" as UCA3
}


UC11 ..> UC2 : <<include>>
UC12 ..> UC2 : <<include>>
UC13 ..> UC2 : <<include>>
UC14 ..> UC2 : <<include>>

UC12 <.. UCA3 : <<extend>>
UC13 <.. UCA3 : <<extend>>

G -- UC11
G -- UC12
G -- UC13
G -- UC14
@enduml
