@startuml
skinparam actorStyle awesome

left to right direction

actor Gestore as G

package Sistema {
    usecase "Salvataggio dell'archivio su file" as UC15
    usecase "Caricamento dell'archivio da file" as UC16
    usecase "Scelta del file" as UCA6 

    usecase "Errore di I/O" as UCA5
}


UC15 <.. UCA5 : <<extend>>
UC16 <.. UCA5 : <<extend>>
UC15 <.. UCA6 : <<extend>>
UC16 ..> UCA6 : <<include>>

G -- UC15
G -- UC16

@enduml