@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "Archiviabile<Utente>" as A
participant "Utente" as U
participant "Matricola" as M
participant "IndirizzoEmail" as E
activate G
' ----- Inizio -----

G -> UI : Seleziona l'interazione per\nvisualizzare gli utenti
deactivate G
activate UI
UI -> B : getArchivioUtenti()
activate B
B --> UI : Restituzione archivio degli utenti
deactivate B

UI -> A : getLista()
activate A
A --> UI : Restituzione lista degli utenti
deactivate A

UI -> G : Mostra l'elenco degli utenti
activate G

G -> UI : Interagisce con l'opzione di \naggiunta di un utente
deactivate G

UI -> G : Mostra form di registrazione

loop Inserimento dati (finchè non sono corretti)
    activate G
    G -> UI : Inserisce i dati utente

    activate UI
    UI -> M
    activate M
    M -> M : verifica(matricola)

    M --> UI : matricolaVerificata
    deactivate M

    UI -> E
    activate E
    E -> E : verifica(email)
    E --> UI: emailVerificata
    deactivate E

    break Dati corretti
        UI -> G : Sblocco interazione di conferma
        deactivate UI
    end
end

G -> UI : Conferma la registrazione
deactivate G

' ----- Invio dati a Sistema -----
UI -> U : new Utente(nome,cognome,matricola,email)
activate U
U -> UI : nuovo Utente
deactivate U

' ----- Controllo Matricola -----
UI -> A : registra(Utente)
activate A
alt Matricola già registrata

    A -> UI : throw ValoreGiàPresenteException
    deactivate A

    UI -> G : Visualizzazione errore matricola duplicata
else Matricola unica
    activate A


' ----- Conclusione -----
A --> UI : Corretta registrazione
end
deactivate A
UI -> G : Chisura del form di registrazione
deactivate UI
@enduml
