@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "Archiviabile<Libro>" as A
participant "Libro" as L

'  ---- Flusso principale -----
activate G
G -> UI : Seleziona l'interazione\nper visualizzare i libri
deactivate G
activate UI

UI -> B : getArchivioLibri()
activate B
B --> UI : Restituzione archivio dei libri
deactivate B

UI -> A : getLista()
activate A
A --> UI : Restituzione lista dei libri
deactivate A

UI -> G : Mostra l'elenco dei libri
activate G

G -> UI : Seleziona campo da modificare

note right
I campi di titolo, autori e numero di copie sono
modificabili in modo simile usando la flessibilità
di Consumer.
endnote

G -> UI : Inserisce nuovo valore
deactivate G
UI -> A : modifica(libro, consumer)
activate A

A -> L : consumer.accept(libro)
activate L

alt Campo invalido
    L -> UI : throw IllegalArgumentException
    deactivate L
    deactivate A

    note left
    La modifica al valore viene annullata
    endnote

    UI -> G : Mostra messaggio di errore
else Campo valido
    activate L
    activate A
    L --> UI : Modifica effettuata con successo
    deactivate L
    deactivate A
    UI -> G : Mostra il nuovo valore del campo
end
deactivate UI

@enduml
