@startuml
actor Gestore
participant "GUI" as UI
participant "Biblioteca" as B
participant "ArchivioLibri" as A
participant "Libro" as L

'  ---- Flusso principale -----
activate Gestore
Gestore -> UI : Interazione con "Libri"
deactivate Gestore
activate UI

UI -> B : getArchivioLibri()
activate B
B --> UI : Restituzione elenco dei libri
deactivate B
UI -> Gestore : Mostra l'elenco dei libri
activate Gestore

Gestore -> UI : Seleziona campo Copie Disponibili da modificare
Gestore -> UI : Inserisce nuovo valore
deactivate Gestore
UI -> A : modifica(Libro da modificare, consumer)
activate A

A -> L : consumer.accept(libro)
activate L

alt Numero Copie Libro Invalido
    L -> UI : throw NumeroCopieInvalidoException
    deactivate L
    UI -> Gestore : La modifica al valore viene annullata
    UI -> Gestore : Mostra messaggio di errore
else Campo valido
    L --> UI : Modifica effettuata con successo
    deactivate A
    UI -> Gestore : Mostra il nuovo valore del campo
end
deactivate UI

@enduml
