@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "ArchivioPrestito" as AP
participant "Prestito" as P

'---Modifica prestiti---
G -> UI : Interazione con "Prestiti"
UI -> B : getArchivioPrestiti()
B --> UI : Restituzione elenco dei Prestiti
UI -> G : Visualizza elenco dei prestiti

G -> UI : Selezione campo da modificare
G -> UI : Modifica della data di Scadenza del prestito

'--- Invio all'archivio
UI -> AP : modifica(Prestito da modificare,consumer)
AP -> P : consumer.accept(Prestito)
P -> P : verifica(DataDiScadenza)

'--- Data di scadenza valida---
alt dataDiScadenza non valida
P -> UI : throw DataDiScadenzaInvalidaException
UI -> G : La modifica viene annullata
UI -> G : L'errore viene visualizzato
UI -> G : Visualizzazione della vecchia data


else DataDiScadenza valida
P --> UI : Modifica  effettuata con successo
UI -> G : Mostra il nuovo valore del campo

end
@enduml
