@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "ArchivioLibri" as AL
participant "ArchivioPrestiti" as AP
participant "Prestito" as P

' ----- Inizio -----
activate G
G -> UI : Interazione con l'interazione per visualizzare i libri
deactivate G
activate UI
UI -> B : getArchivioLibri()
activate B

B --> UI : Restituzione dell'elenco dei libri
deactivate B
UI -> G : Mostra l'elenco dei libri
activate G
G -> UI : Seleziona l'utente da rimuovere
deactivate G

'-- ottieni prestito --
UI -> AP : filtra(Libro)
AP -> P : getStatoPrestito()
activate P
P --> UI : Ritorno dello stato del prestito
deactivate P


' ---- Flusso alternativo -----
alt Presenza di un prestito attivo
    UI -> G : Disabilita l'interazione di rimozione del libro

else Nessun prestito attivo
    activate G
    G -> UI : Interazione di rimozione del libro
    deactivate G
    UI -> AL : rimuovi(libro)
    activate AL
    AL --> UI : Rimozione fatta con successo
    deactivate AL 
    UI -> G : Nuova visualizzazione dei libri

end

deactivate UI

@enduml
