@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "Archiviabile<Libro>" as A

' ----- Inizio -----
activate G
G -> UI : Seleziona l'interazione per visualizzare i libri
deactivate G
activate UI
UI -> B : getArchivioLibri()
activate B
B --> UI : Restituzione dell'archivio dei libri
deactivate B

UI -> A : getLista()
activate A
A --> UI : Restituzione lista dei libri
deactivate A

deactivate B
UI -> G : Mostra l'elenco dei libri
activate G
G -> UI : Seleziona il libro da rimuovere
UI -> G : Abilita interazione di rimozione
G -> UI : Interazione di rimozione del libro
deactivate G


UI -> A : rimuovi(libro)
activate A
A --> UI : Rimozione fatta con successo
deactivate A
UI -> G : Nuova visualizzazione dei libri
deactivate UI

@enduml
