@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant  "Archiviabile<Libro>" as A

'  ---- Flusso principale -----
activate G
G -> UI : Seleziona l'interazione per\nvisualizzare l'elenco dei libri
deactivate G
activate UI

UI -> B : getArchivioLibri()
activate B
B --> UI : Restituzione archvio dei libri
deactivate B

UI -> A : getLista()
activate A
A --> UI : Restituzione lista dei libri
deactivate A

UI -> G : Mostra l'elenco dei libri

activate G
'-- Ricerca del libro --
G -> UI : Inserimento dell'ISBN del\nlibro e/o del titolo\nnei campi di ricerca
deactivate G
UI -> A : filtra(filtroLibri : Filtro<Libro>)
activate A
A --> UI : Restituzione la lista filtrata dei libri
deactivate A

UI -> G : Mostra elenco filtrato di libri
deactivate UI


@enduml
