@startuml
actor Gestore as G
participant "GUI" as UI
participant "Biblioteca" as B
participant "Archivio<Prestito>" as A

activate G
G -> UI : Seleziona l'interazione per visualizzare i prestiti
deactivate G
activate UI

UI -> B : getArchivioPrestiti()
activate B
B --> UI : Restituzione elenco prestiti
deactivate B
UI -> A : getLista()
activate A
A --> UI : Restituzione lista dei libri
deactivate A


UI -> G : Visualizzazione dell'elenco dei prestiti
activate G

'-- Restituzione prestito --
G -> UI : Interazione di restituzione del prestito
deactivate G
UI -> A : rimuovi(Prestito)
note left
Per i prestiti, l'operazione di rimozione è
equivalente a quella di restituzione.
endnote
activate A
A --> UI : Restituzione completata con successo
deactivate A
UI -> G : Visualizzazione dell'elenco modificato
@enduml
